---
swagger: "2.0"
info:
  title: "ms-id-token-api-{Environment}"
  version: "1.0.0"
  description: > 
    API for posting okta access tokens and receiving id tokens
schemes:
- https
paths:
  /v1/auth/id-token:
    post:
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-integration:
        credentials: "arn:aws:iam::{AccountId}:role/Swagger-Lambda-Role"      
        responses:
          default:
            statusCode: "200"
        uri: "arn:aws:apigateway:{Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:{Region}:{AccountId}:function:${stageVariables.FunctionSignIDTokenV1}:v1/invocations"        
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"
  /v1/auth/keys:
    get:
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-integration:
        credentials: "arn:aws:iam::{AccountId}:role/Swagger-Lambda-Role"            
        responses:
          default:
            statusCode: "200"
        uri: "arn:aws:apigateway:{Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:{Region}:{AccountId}:function:${stageVariables.FunctionProvidePubKeysV1}:v1/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"
        
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
    
# Added by API Auto Mocking Plugin (updated by mlf to be safe)
basePath: /Elevate8/IdToken/1.0.0
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com