version: 0.2
phases:
  install:
    commands:
      - sed -i "s/{AccountId}/$AccountId/g" api-swagger.yaml
      - more api-swagger.yaml
      - sed -i "s/{Region}/$Region/g" api-swagger.yaml
      - more api-swagger.yaml
      - sed -i "s/{Branch}/$Branch/g" api-swagger.yaml
      - more api-swagger.yaml
      - sed -i "s/{Environment}/$Environment/g" api-swagger.yaml
      - more api-swagger.yaml
  build:
    commands:
      - aws s3 cp s3://$S3ParamBucket/$Repo/$Environment/$ParamFilename $ParamFilename
      - aws cloudformation package --template $InputFile --s3-bucket $S3Bucket --output-template $OutputFile
      - more $OutputFile
artifacts:
  type: zip
  files:
    - $OutputFile
    - $ParamFilename
