version: 0.1
phases:
  install:
    commands:
      - sed "s/{AccountId}/$AccountId/" api-swagger.yaml
      - sed "s/{Region}/$Region/" api-swagger.yaml 
      - aws cloudformation package --template-file template.yaml --s3-bucket $S3_Bucket --output-template-file newtemplate.yaml 
artifacts:
  type: zip
  files:
    - newtemplate.yaml
    - dev_params.json


