AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Spec

Parameters:
    Branch:
        Type: String
    Repo:
        Type: String
        Default: ""

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
        StageName: sandbox
        DefinitionUri: ./api-swagger.yaml
        Variables:
          LambdaAliasV1: v1
          LambdaFunctionNameV1: 
            Fn::Sub: V1-time-lambda2-${Branch}
          LambdaAliasV2: v2
          LambdaFunctionNameV2: 
            Fn::Sub: V2-time-lambda2-${Branch}
          LambdaAliasV3: v3
          LambdaFunctionNameV3: 
            Fn::Sub: V3-time-lambda2-${Branch}
          WebhookCustomAuthorizer: api-key-authorizer
          WebhookFunctionName: Webhook


