AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: core-apigateway
Parameters:
  Branch:
    Type: String
  Repo:
    Type: String
    Default: ""
  Environment:
    Type: String
Resources:
  MsIdTokenApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: default
      DefinitionUri: ./api-swagger.yaml
      Variables:
        baseUrl:
          Fn::Sub: 123-${Environment}.cc

